version: '3.1'
services:
  website:
    image: php:apache
    depends_on:
      - api
    ports:
      - "80:80"
    environment:
      - USERNAME=toto
      - PASSWORD=python
    volumes:
      - ./website:/var/www/html
  api:
    image: simpleapi
    ports:
      - "5000:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json