version: '3.1'
services:
  website:
    image: php:apache
    depends_on:
      - api
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./website:/var/www/html
    networks:
      - student-list-network
  api:
    image: simple_api
    container_name: mini-projet-api
    ports:
      - "5000:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - student-list-network
networks:
  student-list-network: